/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteTokenRouteImport } from './routes/vote.$token'
import { Route as ResultsSessionIdRouteImport } from './routes/results.$sessionId'
import { Route as LobbyTokenRouteImport } from './routes/lobby.$token'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminMapsRouteImport } from './routes/admin/maps'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminSessionSessionIdRouteImport } from './routes/admin/session.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteTokenRoute = VoteTokenRouteImport.update({
  id: '/vote/$token',
  path: '/vote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyTokenRoute = LobbyTokenRouteImport.update({
  id: '/lobby/$token',
  path: '/lobby/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionSessionIdRoute = AdminSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/lobby/$token': typeof LobbyTokenRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/admin/session/$sessionId': typeof AdminSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/lobby/$token': typeof LobbyTokenRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/admin/session/$sessionId': typeof AdminSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/lobby/$token': typeof LobbyTokenRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/vote/$token': typeof VoteTokenRoute
  '/admin/session/$sessionId': typeof AdminSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/maps'
    | '/admin/teams'
    | '/lobby/$token'
    | '/results/$sessionId'
    | '/vote/$token'
    | '/admin/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/maps'
    | '/admin/teams'
    | '/lobby/$token'
    | '/results/$sessionId'
    | '/vote/$token'
    | '/admin/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/maps'
    | '/admin/teams'
    | '/lobby/$token'
    | '/results/$sessionId'
    | '/vote/$token'
    | '/admin/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LobbyTokenRoute: typeof LobbyTokenRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
  VoteTokenRoute: typeof VoteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$token': {
      id: '/vote/$token'
      path: '/vote/$token'
      fullPath: '/vote/$token'
      preLoaderRoute: typeof VoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$token': {
      id: '/lobby/$token'
      path: '/lobby/$token'
      fullPath: '/lobby/$token'
      preLoaderRoute: typeof LobbyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/session/$sessionId': {
      id: '/admin/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/admin/session/$sessionId'
      preLoaderRoute: typeof AdminSessionSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMapsRoute: typeof AdminMapsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminSessionSessionIdRoute: typeof AdminSessionSessionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMapsRoute: AdminMapsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminSessionSessionIdRoute: AdminSessionSessionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LobbyTokenRoute: LobbyTokenRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
  VoteTokenRoute: VoteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
